Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Models/ptb2.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Baitapvntuan3_2_3_4.Models
{
    public class ptb2
    {
        public int a { get; set; }
        public int b { get; set; }
        public int c { get; set; }
    }
}

Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Controllers/BTVNController.cs
using Baitapvntuan3_2_3_4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Baitapvntuan3_2_3_4.Controllers
{
    public class BTVNController : Controller
    {
        // GET: BTVN
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SoHH(int n = 0)
        {
            ViewBag.n = n;
            return View();
        }
        [HttpPost]
        public ActionResult NhanDL_SoHH(int n)
        {
            ViewBag.n = n;
            return View("SoHH");
        }
        public ActionResult SoCP()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult NhanDL_SoCP(string mangnhap)
        {
            ViewBag.mangnhap = mangnhap;
            return View("SoCP");
        }
        public ActionResult gptb2()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NhanDL_gptb2(ptb2 ptb2_)
        {
           ViewBag.a = ptb2_.a;
            ViewBag.b = ptb2_.b;
            ViewBag.c = ptb2_.c;
            return View("gptb2");
        }
    }
}

Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Baitapvntuan3_2_3_4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Views/BTVN/SoCP.cshtml
@{
    ViewBag.Title = "SoCP";
    string mangnhap = ViewBag.mangnhap;
    List<int> socp = new List<int>();
    if (!string.IsNullOrEmpty(mangnhap))
    {
        var mang = mangnhap.Split(',').Where(x => !string.IsNullOrWhiteSpace(x)).Select(int.Parse).ToList();
        bool ktrascp(int number)
        {
            int sqrt = (int)Math.Sqrt(number);
            return sqrt * sqrt == number;
        }
        foreach (var so in mang)
        {
            if (ktrascp(so))
            {
                socp.Add(so);
            }
        }
    }
}

<h2>SoCP</h2>

@{ Html.BeginForm("NhanDL_SoCP","BTVN", FormMethod.Post);}
<br />
<label>Nhập các phần tử của mảng</label>
<input type="text" id="mangnhap" name="mangnhap" value="@mangnhap" required />
<br />
<input type="submit" value="Tìm số chính phương" />
@{ Html.EndForm();}

@if (!string.IsNullOrEmpty(mangnhap))
{
    <h3>Kết quả:</h3>
    if (socp.Count > 0)
    {
        <p>Các sô chính phương trong mảng là: @string.Join(", ", socp)</p>
    }
    else
    {
        <p>Không có số chính phương nào trong mảng!</p>
    }
}

Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Views/BTVN/SoHH.cshtml
@{
    ViewBag.Title = "SoHH";
    int? n = ViewBag.n;
    List<int> sohh = new List<int>();
    bool ktrashh(int number)
    {
        int sum = 0;
        for (int i = 1; i <= number/2; i++)
        {
            if(number % i == 0)
            {
                sum += i;
            }
        }
        return sum == number;
    }
    if (n.HasValue)
    {
        for (int i = 1; i < n.Value; i++)
        {
            if (ktrashh(i))
            {
                sohh.Add(i);
            }
        }
    }
}

<h2>SoHH</h2>
@{ Html.BeginForm("NhanDL_SoHH","BTVN",FormMethod.Post);}
<br />
<label>Nhập số n</label>
<input type="number" id="n" name="n" required />
<br />
<input type="submit" value="Tìm số hoàn hảo" />
@{ Html.EndForm();}
@if (n.HasValue)
            {
                <h3>Kết quả:</h3>
                if(sohh.Count > 0)
                {
                    <p>Các sô hoàn hảo trong khoảng từ 1 đến @n là: @string.Join(", ",sohh) </p>
    }
    else
                {
        <p>Không có số hoản hảo trong khoảng từ 1 đến @n</p>
                }
            }

Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Views/BTVN/gptb2.cshtml
@model Baitapvntuan3_2_3_4.Models.ptb2
@{
    ViewBag.Title = "gptb2";
}

<h2>gptb2</h2>
@{ Html.BeginForm("NhanDL_gptb2", "BTVN", FormMethod.Post);}
@Html.LabelFor(m => m.a)
@Html.EditorFor(m => m.a)
<br />
@Html.LabelFor(m => m.b)
@Html.EditorFor(m => m.b)
<br />
@Html.LabelFor(m => m.c)
@Html.EditorFor(m => m.c)
<br />
<input type="submit" value="Giải phương trình" />
@{ Html.EndForm();}

@if (ViewBag.a != null && ViewBag.b != null && ViewBag.c != null)
{
    double a = (double)ViewBag.a;
    double b = (double)ViewBag.b;
    double c = (double)ViewBag.c;
    double delta = b * b - 4 * a * c;
    if (a == 0)
    {
        double x1 = -b / c;
        <h3>Kết quả</h3>
        <p> Phương trình có nghiệm x = @x1</p>
    }
    else if (delta == 0)
    {
        double x2 = -b / (2 * a);
        <h3>Kết quả</h3>
        <p> Phương trình có nghiệm kép x1 = x2 = @x2</p>
    }
    else if (delta < 0)
    {
        <h3>Kết quả</h3>
        <p> Phương trình vô nghiệm</p>
    }
    else
    {
        double x3 = (-b + Math.Sqrt(delta))/(2*a);
        double x4 = (-b - Math.Sqrt(delta)) / (2 * a);
        <h3>Kết quả</h3>
        <p> Phương trình có nghiệm kép x1 = @x3, x2 = @x4</p>
    }
}

Baitapvntuan3_2_3_4/Baitapvntuan3_2_3_4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>