BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Models/BanHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BTVN_tuan6__30_10_2024.Models
{
    public class BanHang
    {
        [Key,Column(Order = 0)]
        [StringLength(4)]
        public string Manv { get; set; }
        [Key, Column(Order = 1)]
        [StringLength(5)]
        public string Masp { get; set; }
        public short Dinhmuc { get; set; }
        public short Slban { get; set; }
        [ForeignKey("Manv")]
        public virtual NhanVien NhanVien { get; set; }
        [ForeignKey("Masp")]
        public virtual SanPham SanPham { get; set; }
    }
}

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Controllers/BanHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTVN_tuan6__30_10_2024.Models;

namespace BTVN_tuan6__30_10_2024.Controllers
{
    public class BanHangsController : Controller
    {
        private ShopDbContext db = new ShopDbContext();

        // GET: BanHangs
        public ActionResult Index()
        {
            var banHangs = db.BanHangs.Include(b => b.NhanVien).Include(b => b.SanPham);
            return View(banHangs.ToList());
        }

        // GET: BanHangs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BanHang banHang = db.BanHangs.Find(id);
            if (banHang == null)
            {
                return HttpNotFound();
            }
            return View(banHang);
        }

        // GET: BanHangs/Create
        public ActionResult Create()
        {
            ViewBag.Manv = new SelectList(db.NhanViens, "Manv", "Tenquay");
            ViewBag.Masp = new SelectList(db.SanPhams, "Masp", "Tensp");
            return View();
        }

        // POST: BanHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Manv,Masp,Dinhmuc,Slban")] BanHang banHang)
        {
            if (ModelState.IsValid)
            {
                db.BanHangs.Add(banHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Manv = new SelectList(db.NhanViens, "Manv", "Tenquay", banHang.Manv);
            ViewBag.Masp = new SelectList(db.SanPhams, "Masp", "Tensp", banHang.Masp);
            return View(banHang);
        }

        // GET: BanHangs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BanHang banHang = db.BanHangs.Find(id);
            if (banHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.Manv = new SelectList(db.NhanViens, "Manv", "Tenquay", banHang.Manv);
            ViewBag.Masp = new SelectList(db.SanPhams, "Masp", "Tensp", banHang.Masp);
            return View(banHang);
        }

        // POST: BanHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Manv,Masp,Dinhmuc,Slban")] BanHang banHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(banHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Manv = new SelectList(db.NhanViens, "Manv", "Tenquay", banHang.Manv);
            ViewBag.Masp = new SelectList(db.SanPhams, "Masp", "Tensp", banHang.Masp);
            return View(banHang);
        }

        // GET: BanHangs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BanHang banHang = db.BanHangs.Find(id);
            if (banHang == null)
            {
                return HttpNotFound();
            }
            return View(banHang);
        }

        // POST: BanHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BanHang banHang = db.BanHangs.Find(id);
            db.BanHangs.Remove(banHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Search(string key)
        {

            if (string.IsNullOrEmpty(key))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest) ;
            }
            var banHangs = db.BanHangs.Include(b =>b.NhanVien).Include(b => b.SanPham).Where(b => b.SanPham.Tensp.Contains(key) || b.SanPham.Masp.Contains(key)).ToList();
            return View(banHangs);
        }
        public ActionResult TongSoLuongBanTheoNhanVien()
        {
            var kq = db.BanHangs.GroupBy(b => b.NhanVien).Select(g => new {HoTen = g.Key.Hoten, TongSoLuongBan = g.Sum(b => b.Slban)}).ToList();
            ViewBag.NhanVien = kq.Select(r => r.HoTen).ToList();
            ViewBag.TongSoLuongBan = kq.Select(r => r.TongSoLuongBan).ToList();
            return View();
        }

        public ActionResult BanHangVuotDinhMuc()
        {
            var kq = db.BanHangs.Where(b => b.Slban > b.Dinhmuc).OrderByDescending(b => b.Slban).ToList();
            return View(kq);
        }
        public ActionResult MatHangBanNhieuNhat()
        {
            var kq = db.BanHangs.GroupBy(b => b.SanPham.Tensp).Select(g => new { Tensp = g.Key, TongSoLuong = g.Sum(b => b.Slban) }).OrderByDescending(g => g.TongSoLuong).Take(1).ToList();
            ViewBag.TenSanPham = kq[0].Tensp;
            ViewBag.TongSoLuong = kq[0].TongSoLuong;
            return View();
        }


    }
}

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/BanHangVuotDinhMuc.cshtml
@model IEnumerable<BTVN_tuan6__30_10_2024.Models.BanHang>

@{
    ViewBag.Title = "BanHangVuotDinhMuc";
}

<h2>BanHangVuotDinhMuc</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NhanVien.Tenquay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SanPham.Tensp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dinhmuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slban)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NhanVien.Tenquay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SanPham.Tensp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dinhmuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Slban)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/Create.cshtml
@model BTVN_tuan6__30_10_2024.Models.BanHang

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BanHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Manv, "Manv", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Manv", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Manv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Masp, "Masp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Masp", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Masp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dinhmuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dinhmuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dinhmuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/Delete.cshtml
@model BTVN_tuan6__30_10_2024.Models.BanHang

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BanHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NhanVien.Tenquay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanVien.Tenquay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SanPham.Tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPham.Tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dinhmuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dinhmuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slban)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/Details.cshtml
@model BTVN_tuan6__30_10_2024.Models.BanHang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BanHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NhanVien.Tenquay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanVien.Tenquay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SanPham.Tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPham.Tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dinhmuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dinhmuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slban)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/Edit.cshtml
@model BTVN_tuan6__30_10_2024.Models.BanHang

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BanHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Manv)

        @Html.HiddenFor(model => model.Masp)

        <div class="form-group">
            @Html.LabelFor(model => model.Dinhmuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dinhmuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dinhmuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/Index.cshtml
@model IEnumerable<BTVN_tuan6__30_10_2024.Models.BanHang>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NhanVien.Tenquay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SanPham.Tensp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dinhmuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slban)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NhanVien.Tenquay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SanPham.Tensp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dinhmuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Slban)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/MatHangBanNhieuNhat.cshtml
@model IEnumerable<BTVN_tuan6__30_10_2024.Models.BanHang>
@{
    ViewBag.Title = "MatHangBanNhieuNhat";
}

<h2>MatHangBanNhieuNhat</h2>

<h3>Tên sản phẩm: @ViewBag.TenSanPham</h3>
<h3>Tổng số lượng bán: @ViewBag.TongSoLuong</h3>

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/Search.cshtml
@model IEnumerable<BTVN_tuan6__30_10_2024.Models.BanHang>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
@using (@Html.BeginForm("Search", "BanHangs", FormMethod.Post))
{ 
    <div>
        <label>Nhập tên sản phẩm:</label>
        <input type="text" id="key" name="key" required />
        <input type="submit" value="Tìm kiếm" />
    </div>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (Model != null && Model.Any())
{
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NhanVien.Tenquay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SanPham.Tensp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dinhmuc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slban)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NhanVien.Tenquay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SanPham.Tensp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dinhmuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Slban)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>
}

BTVN_tuan6 -30_10_2024/BTVN_tuan6 -30_10_2024/Views/BanHangs/TongSoLuongBanTheoNhanVien.cshtml
@model IEnumerable<BTVN_tuan6__30_10_2024.Models.BanHang>

@{
    ViewBag.Title = "TongSoLuongBanTheoNhanVien";
}

<h2>TongSoLuongBanTheoNhanVien</h2>
<h3>Thông tin từ ViewBag: </h3>
<ul>
    @for (int i = 0; i < ViewBag.NhanVien.Count; i++)
    {
        <li>@ViewBag.NhanVien[i] : @ViewBag.TongSoLuongBan[i] </li>

    }
</ul>